# Generated by Django 2.1.5 on 2019-02-17 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20190216_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_date',
        ),
        migrations.AddField(
            model_name='bookedusers',
            name='booked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 10, 11, 13, 885430, tzinfo=utc)),
        ),
    ]
