# Generated by Django 2.1.5 on 2019-02-21 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20190221_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlink',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='bookedusers',
            name='booked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 12, 3, 25, 174145, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='AdminLink',
        ),
    ]
