# Generated by Django 2.1.5 on 2019-02-21 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20190221_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedusers',
            name='booked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 12, 4, 6, 980013, tzinfo=utc)),
        ),
    ]
