# Generated by Django 2.1.5 on 2019-02-22 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20190221_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedusers',
            name='booked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 15, 31, 29, 877848, tzinfo=utc)),
        ),
    ]
