# Generated by Django 2.1.5 on 2019-02-23 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20190223_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedusers',
            name='booked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 16, 16, 38, 384412, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_no', 'block')},
        ),
    ]
