# Generated by Django 2.1.5 on 2019-02-24 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20190223_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedusers',
            name='booked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 6, 29, 6, 496595, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookedusers',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
