# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20190407_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user_booked',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
