# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_auto_20190408_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='uploads/id_proofs'),
        ),
    ]
