# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-14 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_bookings_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='checkedin',
            field=models.BooleanField(default=False),
        ),
    ]
