# Generated by Django 2.1.5 on 2019-04-15 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_bookings_checkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedrooms',
            name='blocked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
