# Generated by Django 2.1.5 on 2019-02-16 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mobileverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 13, 43, 17, 762860, tzinfo=utc)),
        ),
    ]
