# Generated by Django 2.1.5 on 2019-02-17 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mobileverification_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 10, 11, 13, 859429, tzinfo=utc)),
        ),
    ]
