# Generated by Django 2.1.5 on 2019-02-21 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190217_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 12, 1, 52, 850562, tzinfo=utc)),
        ),
    ]
