# Generated by Django 2.1.5 on 2019-02-21 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190221_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 12, 3, 25, 171168, tzinfo=utc)),
        ),
    ]
