# Generated by Django 2.1.5 on 2019-02-21 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190221_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileverification',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminlink',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 15, 40, 20, 45762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 15, 40, 20, 45199, tzinfo=utc)),
        ),
    ]
