# Generated by Django 2.1.5 on 2019-02-22 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190221_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileverification',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminlink',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 15, 31, 29, 875394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 22, 15, 31, 29, 874865, tzinfo=utc)),
        ),
    ]
