# Generated by Django 2.1.5 on 2019-02-23 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190222_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlink',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 16, 11, 49, 818246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 16, 11, 49, 817720, tzinfo=utc)),
        ),
    ]
