# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190407_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlink',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 8, 17, 19, 601985)),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 8, 17, 19, 601342)),
        ),
    ]
