# Generated by Django 2.1.5 on 2019-04-15 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190414_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlink',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 0, 50, 12, 453773)),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 0, 50, 12, 453100)),
        ),
    ]
